# This is the config file for timeshift-spaceshift
# This file is created by the timeshift-spaceshift script.
# the disk usage warning limit is set to 90% by default.
# the disk usage limit is set to 95% by default.
# the snapshot limit is set to 3 by default. There will remain at least 3 snapshots.
DISK_USAGE_WARNING_LIMIT=90
DISK_USAGE_LIMIT=95
SNAPSHOT_LIMIT=3